/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001c3b",
        "secondary-fixed": "#dae2fd",
        "surface-bright": "#fff8f6",
        "surface-dim": "#f3d3cb",
        "surface-container-high": "#ffe2db",
        "on-surface-variant": "#5d4039",
        "primary-fixed-dim": "#ffb4a2",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-tint": "#b52700",
        "on-tertiary-fixed-variant": "#004787",
        "surface-variant": "#fcdbd4",
        "outline-variant": "#e7bdb4",
        "on-tertiary": "#ffffff",
        "primary-container": "#dd3200",
        "on-error-container": "#93000a",
        "surface-container": "#ffe9e4",
        "inverse-on-surface": "#ffede9",
        surface: "#fff8f6",
        "primary-fixed": "#ffdad2",
        "on-surface": "#281713",
        "surface-container-low": "#fff0ed",
        primary: "#b02600",
        "on-primary-fixed": "#3d0700",
        "on-primary-fixed-variant": "#8a1c00",
        background: "#fff8f6",
        tertiary: "#005cac",
        secondary: "#565e74",
        "surface-container-highest": "#fcdbd4",
        "on-secondary-container": "#5c647a",
        error: "#ba1a1a",
        "inverse-surface": "#402c27",
        "error-container": "#ffdad6",
        "secondary-container": "#dae2fd",
        "on-error": "#ffffff",
        outline: "#926f67",
        "tertiary-container": "#0075d7",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#a6c8ff",
        "on-background": "#281713",
        "inverse-primary": "#ffb4a2",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed": "#131b2e",
      },
      spacing: {
        unit: "4px",
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-page": "40px",
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        display: ["Inter", "system-ui", "sans-serif"],
        h1: ["Inter", "system-ui", "sans-serif"],
        h2: ["Inter", "system-ui", "sans-serif"],
        h3: ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        h3: ["18px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        mono: ["13px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}

